# Generated by Django 5.1.1 on 2025-05-28 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='все форматы(кроме svg) конвертируются в webp', upload_to='images/%Y/%m/%d/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('main', models.BooleanField(default=False, verbose_name='главный проект?')),
                ('direction', models.CharField(max_length=255, verbose_name='направление')),
                ('location', models.CharField(max_length=255, verbose_name='локация')),
                ('status', models.CharField(max_length=255, verbose_name='статус')),
                ('square', models.CharField(max_length=255, verbose_name='площадь')),
                ('year', models.CharField(max_length=255, verbose_name='год')),
                ('photos', models.ManyToManyField(to='projects.imagemodel', verbose_name='фотографии проекта')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
            },
        ),
    ]
