# Generated by Django 5.1.1 on 2025-07-02 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0004_contact'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='photos',
            field=models.ManyToManyField(blank=True, to='projects.imagemodel', verbose_name='фотографии проекта'),
        ),
        migrations.CreateModel(
            name='ProjectBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('photos', models.ManyToManyField(blank=True, to='projects.imagemodel', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'Страницы для проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='ссылка на проект')),
                ('description', models.CharField(max_length=255, verbose_name='краткое описание проекта')),
                ('cektor', models.CharField(max_length=255, verbose_name='сектор')),
                ('blocks', models.ManyToManyField(to='projects.projectblocks', verbose_name='блоки проекта на странице')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_page', to='projects.project', verbose_name='Проект')),
                ('slider_one', models.ManyToManyField(blank=True, related_name='project_slider_one', to='projects.imagemodel', verbose_name='фотографии проекта')),
                ('slider_two', models.ManyToManyField(blank=True, related_name='project_slider_two', to='projects.imagemodel', verbose_name='фотографии чертежей и фасадов')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'Страницы для проектов',
            },
        ),
        migrations.CreateModel(
            name='ProjectPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Позиция')),
                ('empl', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='about_app.employees', verbose_name='участник')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'Страницы для проектов',
            },
        ),
    ]
