# Generated by Django 5.1.1 on 2025-07-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_photos_projectblocks_projectpage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectblocks',
            options={'verbose_name': 'блок', 'verbose_name_plural': 'Блоки на страницах проектов'},
        ),
        migrations.AlterModelOptions(
            name='projectpeople',
            options={'verbose_name': 'участник', 'verbose_name_plural': 'Участники команды для проектов'},
        ),
        migrations.AlterField(
            model_name='projectpage',
            name='description',
            field=models.TextField(verbose_name='краткое описание проекта'),
        ),
    ]
