# Generated by Django 5.1.1 on 2025-07-02 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projectblocks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectblocks',
            name='photos',
        ),
        migrations.AddField(
            model_name='projectblocks',
            name='photo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.imagemodel', verbose_name='фото'),
            preserve_default=False,
        ),
    ]
