# Generated by Django 5.1.1 on 2025-07-02 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_projectblocks_photos_projectblocks_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectblocks',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.imagemodel', verbose_name='фото'),
        ),
    ]
