# Generated by Django 5.1.1 on 2025-07-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_projectblocks_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='command',
            field=models.ManyToManyField(to='projects.projectpeople', verbose_name='команда проекта'),
        ),
    ]
