# Generated by Django 5.1.1 on 2025-07-02 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectpage_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpeople',
            name='empl',
            field=models.CharField(max_length=255, verbose_name='имя'),
        ),
    ]
