# Generated by Django 5.1.6 on 2025-07-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projectpeople_empl'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='view',
            field=models.BooleanField(default=False, help_text='Сделать видимым на сайте', verbose_name='Отображать?'),
        ),
    ]
