# Generated by Django 5.1.1 on 2025-05-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PagesMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='страница')),
                ('title', models.CharField(max_length=255, verbose_name='тег title страницы')),
                ('desc', models.TextField(verbose_name='тег description страницы')),
            ],
            options={
                'verbose_name': 'страница',
                'verbose_name_plural': 'описание страниц',
            },
        ),
    ]
