# Generated by Django 5.1.6 on 2025-07-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_meta', '0002_vectorblocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('desc', models.TextField(verbose_name='краткое описание')),
                ('image', models.ImageField(upload_to='index_blocks/', verbose_name='фоновое фото')),
            ],
            options={
                'verbose_name': 'блок',
                'verbose_name_plural': 'Блок с лучшими проектами',
            },
        ),
        migrations.CreateModel(
            name='TehnologyBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='название')),
                ('desc', models.TextField(verbose_name='краткое описание')),
                ('image', models.ImageField(upload_to='index_blocks/', verbose_name='фоновое фото')),
            ],
            options={
                'verbose_name': 'блок',
                'verbose_name_plural': 'Блок с нашими технологиями',
            },
        ),
    ]
