# Generated by Django 5.1.1 on 2025-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_meta', '0003_projectsblocks_tehnologyblocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsblocks',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='projectsblocks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='tehnologyblocks',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='tehnologyblocks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
        migrations.AlterField(
            model_name='vectorblocks',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='краткое описание'),
        ),
        migrations.AlterField(
            model_name='vectorblocks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='название'),
        ),
    ]
