version: '3.8'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    volumes:
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media
    depends_on:
      - backend