version: '3.8'

services:
  backend:
    build: .
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    volumes:
      - ./media:/usr/src/app/media
      - ./static:/usr/src/app/static

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/static
      - ./media:/media
      # - ../../etc/letsencrypt:/etc/ssl:ro
    depends_on:
      - backend