# Generated by Django 5.1.6 on 2025-05-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_app', '0002_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='slug',
            field=models.SlugField(default=1, help_text='например, main-architect', verbose_name='ссылка для вакансии'),
            preserve_default=False,
        ),
    ]
