# Generated by Django 5.1.6 on 2025-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='все форматы(кроме svg) конвертируются в webp', upload_to='images/%Y/%m/%d/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'фото',
            },
        ),
        migrations.CreateModel(
            name='BlogBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('slider', models.BooleanField(default=False, verbose_name='Слайдер?')),
                ('photo', models.ManyToManyField(blank=True, to='blog_app.blogimagemodel', verbose_name='фото')),
            ],
            options={
                'verbose_name': 'блок',
                'verbose_name_plural': 'Блоки на страницах статьи',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='наименование')),
                ('blocks', models.ManyToManyField(to='blog_app.blogblocks', verbose_name='Блоки внутри статьи')),
                ('photo', models.ManyToManyField(blank=True, to='blog_app.blogimagemodel', verbose_name='главная фотография статьи')),
            ],
            options={
                'verbose_name': 'статья',
                'verbose_name_plural': 'статьи',
            },
        ),
    ]
