# Generated by Django 5.1.6 on 2025-07-07 14:30

#import image_cropping.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='blogimagemodel',
        #     name='cropping',
        #     field=image_cropping.fields.ImageRatioField('image', '430x360', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        # ),
        migrations.AlterField(
            model_name='blogblocks',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
