# Generated by Django 5.1.6 on 2025-07-08 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_remove_article_photo_alter_blogimagemodel_cropping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1, verbose_name='ссылка на статью'),
            preserve_default=False,
        ),
    ]
