# Generated by Django 5.1.6 on 2025-07-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view',
            field=models.BooleanField(default=False, verbose_name='Отображать на сайте?'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='дата написания'),
        ),
    ]
